"""包展示元数据下放（批B）自动生成：子字段**结构**声明（无任何展示文案）。

由 `scripts/migrate_pack_field_meta.py --gen-structure` 从基线框架 `field_meta.py` 的
`*_CHILD_LABELS` 表程序化导出。**请勿手改**；框架只提供结构，中文名/说明在各包的
`content/<包>/field_meta.json` 里声明。

表示法：
  · `None`              → 叶子键（存在，无子结构、无文案）；
  · `{key: ...}`        → obj 容器（子键递归）；
  · `{"__list__": {…}}` → list-of-obj 容器（元素子键递归）。
"""

# ruff: noqa: E501  （自动生成：结构 dict 的 pprint 行宽可能超限）

from __future__ import annotations

from typing import Any, Dict

# 模块名 → 子字段结构（模块名由 `*_CHILD_LABELS` 变量名小写化而来）。
CHILD_SPEC: Dict[str, Dict[str, Any]] = {'achievement': {'conditions': {}, 'reward': {}, 'hidden': {}},
 'action': {},
 'checkin': {'rewards': {'daily': {'items': {'id': None, 'count': None}},
                         'streak': {'items': {'id': None, 'count': None}},
                         'monthly_total': {'items': {'id': None, 'count': None}}},
             'period': {}},
 'conditional': {'conditional': {'id': None,
                                 'name': None,
                                 'source': None,
                                 'target': None,
                                 'per_point': None,
                                 'note': None}},
 'dungeon': {'drops': {}, 'entry_limit': {}},
 'effects': {'patch': {'target': None, 'value': None, 'pct': None},
             'actions': {'type': None, 'count': None, 'mark': None, 'target': None},
             'ignore_shield': None,
             'ignore_immune': None},
 'enemies': {'stats': {'hp': None,
                       'mp': None,
                       'str': None,
                       'int': None,
                       'con': None,
                       'spr': None,
                       'foc': None,
                       'agi': None,
                       'luk': None},
             'weakness': {'types': None, 'elements': None},
             'resistance': {'immune': None, 'stun': None},
             'actions': {'action': None,
                         'probability': None,
                         'weight': None,
                         'condition': None,
                         'cooldown': None,
                         'hungry': None},
             'special_actions': {'id': None,
                                 'action': None,
                                 'once': None,
                                 'priority': None,
                                 'trigger_cooldown': None,
                                 'max_triggers': None,
                                 'chain_ref': None,
                                 'desc': None,
                                 'trigger': {'type': None,
                                             'value': None,
                                             'timing': None,
                                             'action': None,
                                             'chance': None,
                                             'which': None,
                                             'side': None,
                                             'height': None,
                                             'mark': None,
                                             'min': None,
                                             'absent': None},
                                 'post_state': {'state': None, 'turns': None}},
             'chains': {'id': None,
                        'actions': {'action': None, 'chance': None, 'role': None, 'armor': None}},
             'drops': {'battle': {'item': None, 'chance': None, 'condition': None, 'count': None},
                       'special': {'item': None, 'chance': None, 'condition': None, 'count': None},
                       'death': {'item': None, 'chance': None, 'condition': None, 'count': None}},
             'lore': {'unlock': None, 'desc': None},
             'parts': {'id': None,
                       'name': None,
                       'break_threshold': None,
                       'target_priority': None,
                       'positions': {'side': None, 'height': None},
                       'on_break': {'knockdown': None, 'marks': None, 'effects': None}},
             'ai': {'transitions': {'__list__': {'from': None, 'to': None, 'condition': None}}},
             'phases': {'threshold': None,
                        'enter_action': None,
                        'broadcast': None,
                        'actions': {'__list__': {'action': None,
                                                 'weight': None,
                                                 'probability': None}}},
             'rewards': {'exp': None},
             'zone_change': {'enabled': None,
                             'hp_threshold': None,
                             'targets': None,
                             'timing': None}},
 'enhance': {'cost': {'coin_per_level': None,
                      'stones_per_level': None,
                      'stone_tiers': {'item': None, 'levels': None, 'tier': None}},
             'settings': {'fail_tier_split': None,
                          'level_gated': None,
                          'luck_affects': None,
                          'shatter_mode': None,
                          # 批43 H3：品质等级 → 强化上限（六档）替换 max_by_rarity
                          'max_by_quality_level': {'1': None, '2': None, '3': None,
                                                   '4': None, '5': None, '6': None},
                          # 批43：旧品质枚举 → 品质等级（旧档兼容桥接）
                          'legacy_quality_level_by_rarity': {'normal': None,
                                                             'fine': None,
                                                             'epic': None,
                                                             'legendary': None},
                          # 批43：特殊词条跨度（每 N 级一条）
                          'special_affix_span': None},
             'success_curve': {'rate': None, 'to': None},
             'values': {'weapon_atk_per_level': {'stat_key': None, 'type': None, 'value': None},
                        'armor_def_per_level': {'stat_key': None, 'type': None, 'value': None}}},
 'fishing': {'species': {'id': None,
                         'name': None,
                         'rarity': None,
                         'king': None,
                         'hours': None,
                         'periods': None,
                         'seasons': None,
                         'spots': None,
                         'preferred_bait': None,
                         'size_min': None,
                         'size_max': None,
                         'weight_min': None,
                         'weight_max': None,
                         'codex_text': {'best_mask': None, 'desc': None, 'unit': None}},
             'king': {'id': None,
                      'enabled': None,
                      'chance': None,
                      'hint': None,
                      'enemy_id': None,
                      'species_id': None,
                      'window_daily': None}},
 'forge': {'trees': {'id': None,
                     'name': None,
                     'type': None,
                     'roots': None,
                     'nodes': {'id': None,
                               'name': None,
                               'item': None,
                               'output_item': None,
                               'type': None,
                               'level': None,
                               'parent': None,
                               'branch': None,
                               'stats': None,
                               'slots': {'level': None},
                               'materials': {'item': None,
                                             'count': None,
                                             'tier': None,
                                             'source_override': None},
                               'cost': {},
                               'rarity': None,
                               'monster_source': None,
                               'final': None,
                               'augmentable': None,
                               'king_only': None,
                               'final_tier': None}},
           'sets': {'id': None,
                    'name': None,
                    'variant': None,
                    'pieces': None,
                    'skills': {'piece_count': None,
                               'skill': None,
                               'level': None,
                               'effect_ref': None},
                    'desc': None,
                    'enabled': None,
                    'codex_group': None},
           'augments': {'augments': {'id': None,
                                     'name': None,
                                     'kind': None,
                                     'effect': None,
                                     'stat_key': None,
                                     'value': None,
                                     'cost': {'item': None, 'count': None},
                                     'repeatable': None,
                                     'max_repeat': None,
                                     'slot_level': None,
                                     'disabled': None,
                                     'trace': None},
                        'limit_by_rarity': {'quality': None, 'times': None, 'final_only': None}},
           'settings': {}},
 'jobs': {'growth': {'str': None,
                     'int': None,
                     'con': None,
                     'spr': None,
                     'foc': None,
                     'agi': None,
                     'lck': None,
                     'hp': None,
                     'mp': None},
          'transform': {'transform_skill': None,
                        'transform_to': None,
                        'duration': None,
                        'turns': None,
                        'revert': None,
                        'cooldown': None,
                        'dispel_reverts': None,
                        'skill_set': None,
                        'equip_restrict': None,
                        'derive_chains': None,
                        'state_policy': {'combo': None, 'marks': None, 'buff': None}}},
 'manifest': {'module_tree': {'module': None, 'label': None, 'children': None},
              'module_groups': {'module': None, 'label': None, 'children': None}},
 'maps': {'monsters': {'enemy': None,
                       'count': None,
                       'respawn_minutes': None,
                       'name': None,
                       'hidden_boss': None,
                       'intro': None,
                       'signal': None},
          'exits': {'up': {'to': None, 'mode': None, 'condition': None},
                    'down': {'to': None, 'mode': None, 'condition': None},
                    'left': {'to': None, 'mode': None, 'condition': None},
                    'right': {'to': None, 'mode': None, 'condition': None}},
          'mechanics': {'id': None, 'desc': None, 'on_step': {'type': None, 'damage': None}},
          'gather_points': {'id': None, 'item': None, 'rarity': None, 'rate': None},
          'dungeon_entrances': {'dungeon': None, 'name': None},
          'camp': {'name': None, 'safe': None, 'unlock': None}},
 'marks': {},
 'npc': {'dialogues': {'greeting': {},
                       'options': {'text': None,
                                   'next': None,
                                   'action': None,
                                   'quests': None,
                                   'shop_refs': None,
                                   'intel_refs': None,
                                   'tutorials': None,
                                   'heal': None,
                                   'cost': None}},
         'interactions': {'action': None,
                          'text': None,
                          'repeat': None,
                          'turns': None,
                          'map': None,
                          'items': None,
                          'effects': None,
                          'quests': {'quest_id': None},
                          'condition': {'var': None, 'op': None, 'value': None, 'param': None},
                          'cost': {'coins': None},
                          'heal': {'hp': None, 'mp': None}},
         'quests': {'quest_id': None}},
 'proficiency': {'sp_panel': {'id': None,
                              'name': None,
                              'cost': None,
                              'repeatable': None,
                              'max_repeat': None,
                              'desc': None},
                 'energy': {'enabled': None, 'max_by_tier': None, 'regen_sec': None},
                 'titles': {'id': None, 'name': None, 'icon': None, 'source': None, 'desc': None}},
 'quest': {'conditions': {'var': None, 'op': None, 'value': None, 'param': None},
           'npc': {'id': None},
           'reward': {'coins': None,
                      'gem': None,
                      'exp': None,
                      'rep': None,
                      'prof': None,
                      'item': None,
                      'count': None}},
 'recipe': {'materials': {'id': None, 'item': None, 'count': None},
            'inputs': {'item': None, 'count': None},
            'output': {'item': None, 'count': None},
            'cost': {'coins': None, 'gem': None},
            'evolve_to': {'id': None, 'condition': {'count': None, 'source': None}}},
 'settings': {'currencies': {'id': None, 'name': None, 'icon': None, 'cap': None, 'note': None},
              'death_penalty': {'weak_duration_sec': None,
                                'drop_currency': {'currency': None, 'ratio': None},
                                'drop_exp': {'enabled': None, 'percent': None},
                                'drop_items': {'enabled': None, 'count': None}},
              'alchemy': {'mode': None,
                          'quality_tiers': None,
                          'quality_coef': None,
                          'chain_map': None,
                          'pp_cost': {'normal': None, 'super': None},
                          'pp_refresh': None,
                          'energy_enabled': None,
                          'energy_max': None,
                          'energy_regen_sec': None,
                          'energy_regen_sec_safe': None,
                          'decompose_rate': None,
                          'catalyst_unlock_tier': None,
                          'catalyst_consume': None,
                          'gem.分解': None,
                          'gem.复制': None,
                          'gem.成品合成': None,
                          'gem.配方合成': None,
                          'gem.特性合成': None,
                          'gem.珠升阶': None,
                          'gem.复制额外': None,
                          'copy_extra_cost': None,
                          'gem.decompose_formula': None,
                          'gem_diminish': {'n': None, 'mult': None},
                          'synth_exp': None,
                          'sp_per_level': None,
                          'sp_panel': {'id': None,
                                       'name': None,
                                       'cost': None,
                                       'repeatable': None,
                                       'max_repeat': None,
                                       'desc': None},
                          '战斗道具': {'强度公式': None, '珠触发上限': None},
                          '战斗即时调合': {'auto_use': None,
                                     'per_battle_limit': None,
                                     'proficiency_multiplier': {'min': None,
                                                                'max': None,
                                                                'curve': None}},
                          'max_qty': None,
                          'job_tier_map': None,
                          'farming': {'enabled': None,
                                      'harvest_sec': None,
                                      'plots_max': None,
                                      'trait_inherit': None,
                                      'greenhouse': {'copy_cost': {'coins': None, 'gem': None},
                                                     'copy_slot': None,
                                                     'unlock_tier': None}}},
              'forge': {'forge_fee': None,
                        'synth_ratio_3to1': None,
                        'straight_forge': None,
                        'decompose_rate': None,
                        'exp_per_forge': None,
                        'sets_enabled': None,
                        'augments_enabled': None,
                        'set_piece_counts': None,
                        'set_tier_exact': None},
              'fishing': {'mode': None,
                          'bait_ids': None,
                          'daily_limit': None,
                          'wait_sec': {'min': None, 'max': None},
                          'energy': {'enabled': None},
                          'bait_bonus': {'gold': None, 'rare': None},
                          'rod_full_bonus': {'gold': None, 'rare': None},
                          'crown_thresholds': {'reverse': None, 'silver': None, 'gold': None},
                          'king_event': {'enabled': None, 'window_daily': None, 'chance': None}},
              'assistant': {'enabled': None,
                            'energy_items': None,
                            'unlock_tier': None,
                            'helpers': {'__list__': {'id': None,
                                                     'name': None,
                                                     'desc': None,
                                                     'tier': None,
                                                     'gather_rate': None,
                                                     'quality_bonus': None,
                                                     'trait_bonus': None}},
                            'queue': {'max_slots': None, 'tick_sec': None}},
              'battle': {'stun_enabled': None,
                         'stun_base_threshold': None,
                         'enrage_damage_mult': None,
                         'enrage_recovery_mult': None,
                         'fatigue_recovery_mult': None,
                         'fatigue_stagger_chance': None,
                         'rage_cool_actions': None,
                         'rage_per_damage': None,
                         'roar_combo_clear': None,
                         'roar_heavy_delay': None,
                         'roar_light_delay': None,
                         'stamina_drain_blunt': None,
                         'stamina_max': None,
                         'stamina_regen_per_action': None,
                         'stun_back_mult': None,
                         'stun_decay_per_action': None,
                         'stun_escalation': None,
                         'stun_hint_at': None,
                         'stun_ko_skip': None,
                         'stun_ko_window': None,
                         'stun_side_mult': None,
                         'backstab_bonus': None,
                         'crit_cond_low_hp': None,
                         'min_damage': None},
              'command_aliases': {},
              'contest': {'enabled': None,
                          'reward': {'gem': None,
                                     'title': None,
                                     'reputation': {'submit': None, 'win': None}},
                          'score_weights': {'awaken': None,
                                            'potential': None,
                                            'quality': None,
                                            'trait': None}},
              'ctb': {'enabled': None, 'default_recovery': None},
              'events': {},
              'exp_curve': {},
              'level_cap': None,
              'quest_board': {'enabled': None,
                              'refresh_days': None,
                              'penalty': None,
                              'active_limit': None,
                              'daily_limit': None,
                              'rep_levels': None,
                              'grade_bonus': {'S': None, 'A': None, 'B': None},
                              'tiers': {'__list__': {'id': None,
                                                     'name': None,
                                                     'desc': None,
                                                     'job_level': None,
                                                     'rep_base': None,
                                                     'rep_min': None,
                                                     'star': None,
                                                     'reward': None,
                                                     'require': {'count': None,
                                                                 'item': None,
                                                                 'quality': None}}}}},
 'shop': {'items': {'sold_out_once': None}, 'refresh': {}, 'pool': {}},
 'skill_chains': {'steps': {'from': None,
                            'to': None,
                            'tag': None,
                            'priority': None,
                            'mode': None,
                            'armor': None,
                            'consume': None,
                            'condition': {'count': None},
                            'variant_override': {'power': None}}},
 'skills': {'level': {'max': None, 'growth': None},
            'trigger_limit': {'per_round': None, 'per_battle': None},
            'effects': {'type': None,
                        'effect': None,
                        'target': None,
                        'count': None,
                        'pct': None,
                        'mark': None,
                        'status_id': None,
                        'marks_on': None,
                        'polarity': None,
                        'overrides': None},
            'consume_marks': {}},
 'slots': {'slots': {'slot_level': None}},
 'statuses': {'duration': {'turns': None, 'charges': None}},
 'traits': {}}

__all__ = ["CHILD_SPEC"]
